import { readFile } from 'node:fs/promises';
import { assertFails, assertSucceeds, initializeTestEnvironment } from '@firebase/rules-unit-testing';
import { ref, get, set, update } from 'firebase/database';
const [host, port] = (process.env.FIREBASE_DATABASE_EMULATOR_HOST || '127.0.0.1:9000').split(':');
const env = await initializeTestEnvironment({ projectId: 'demo-preciencia1', database: { host, port: Number(port), rules: await readFile(new URL('../database.rules.json', import.meta.url), 'utf8') } });
const db = id => env.authenticatedContext(id).database(`http://${host}:${port}?ns=demo-preciencia1-default-rtdb`);
const admin = db('teacher'), phone = db('phone'), other = db('other'), pc = db('student');
const base = 'mobileSessions/EVAL-TEST', now = Date.now();
try {
  await env.withSecurityRulesDisabled(async c => {
    const root = c.database(`http://${host}:${port}?ns=demo-preciencia1-default-rtdb`);
    await set(ref(root, 'admins/teacher'), true);
    await set(ref(root, 'sessions/EVAL-TEST/config'), { homeUrl: 'https://example.edu', active: true });
    await set(ref(root, 'sessions/EVAL-TEST/clients/student'), { uid: 'student', id: '123', name: 'Prueba', state: 'locked' });
    await set(ref(root, `${base}/pairs/token`), { claimedBy: 'phone', studentUid: 'student', revoked: false, createdAt: now, inviteExpiresAt: now + 300000, expiresAt: now + 86400000 });
    await set(ref(root, `${base}/links/student`), { token: 'token', inviteExpiresAt: now + 300000 });
    await set(ref(root, 'mobileMembers/EVAL-TEST/phone'), { token: 'token', studentUid: 'student' });
  });
  const status = { connected: true, lastSeen: now, camera: true, visible: true, focused: true, recordingAck: '' };
  await assertSucceeds(get(ref(pc, `${base}/links/student`)));
  await assertFails(get(ref(other, `${base}/links/student`)));
  await assertFails(get(ref(other, `${base}/pairs/token`)));
  await assertSucceeds(get(ref(phone, `${base}/pairs/token`)));
  await assertFails(get(ref(phone, base)));
  await assertFails(set(ref(phone, `${base}/pairs/token/claimedBy`), 'other'));
  await assertFails(set(ref(phone, 'mobileMembers/EVAL-TEST/phone'), { token: 'other', studentUid: 'other' }));
  await assertSucceeds(get(ref(phone, 'sessions/EVAL-TEST/config/active')));
  await assertSucceeds(get(ref(phone, 'sessions/EVAL-TEST/clients/student/state')));
  await assertFails(get(ref(phone, 'sessions/EVAL-TEST/clients/student')));
  await assertSucceeds(set(ref(phone, `${base}/status/token`), status));
  await assertFails(set(ref(other, `${base}/status/token`), status));
  await assertFails(set(ref(phone, `${base}/status/token`), { ...status, image: 'not-allowed' }));
  await assertFails(set(ref(phone, `${base}/status/token`), { ...status, lastSeen: now + 120000 }));
  await assertSucceeds(set(ref(admin, `${base}/rtc/token/viewer`), { id: 'v1', uid: 'teacher', expiresAt: Date.now() + 25000 }));
  await assertFails(set(ref(admin, `${base}/rtc/token/viewer`), { id: 'v2', uid: 'teacher', expiresAt: Date.now() + 25000 }));
  await assertSucceeds(set(ref(admin, `${base}/rtc/token/offer`), { id: 'v1', sdp: 'test-offer' }));
  await assertSucceeds(set(ref(phone, `${base}/rtc/token/answer`), { id: 'v1', sdp: 'test-answer' }));
  await assertFails(set(ref(phone, `${base}/rtc/token/answer`), { id: 'old-viewer', sdp: 'test-answer' }));
  await assertFails(set(ref(phone, `${base}/rtc/token/offer`), { id: 'v1', sdp: 'test-offer' }));
  const command = { id: 'clip', active: true, startedAt: now, viewerId: 'v1' };
  await assertFails(set(ref(phone, `${base}/rtc/token/recording`), command));
  await assertSucceeds(set(ref(admin, `${base}/rtc/token/recording`), command));
  await assertSucceeds(set(ref(phone, `${base}/events/token/1`), { type: 'hidden', ts: now, source: 'mobile' }));
  await assertFails(set(ref(phone, `${base}/events/token/1`), { type: 'visible', ts: now, source: 'mobile' }));
  await assertFails(set(ref(phone, `${base}/events/token/2`), { type: 'hidden', ts: now, source: 'teacher' }));
  await assertFails(set(ref(phone, `${base}/events/token/501`), { type: 'hidden', ts: now, source: 'mobile' }));
  await assertSucceeds(set(ref(phone, `${base}/rtc/token/mobileIce/v1/1`), '{}'));
  await assertFails(set(ref(phone, `${base}/rtc/token/mobileIce/v1/65`), '{}'));
  await assertSucceeds(set(ref(admin, `${base}/pairs/token/revoked`), true));
  await assertFails(set(ref(phone, `${base}/status/token`), status));
  await assertSucceeds(set(ref(admin, `${base}/pairs/token/revoked`), false));
  await assertSucceeds(update(ref(admin, 'sessions/EVAL-TEST/config'), { active: false }));
  await assertFails(set(ref(phone, `${base}/status/token`), status));
  await assertFails(set(ref(phone, `${base}/rtc/token/answer`), { id: 'v1', sdp: 'test-answer' }));
  console.log('Mobile isolation, recording authority, lease, revocation and session closure tests passed.');
} finally { await env.cleanup(); }
